version: "3.4"

services:
  tuckerbackend:
    image: tucker-backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://mongo:27017/tucker
      UI_URL: http://localhost
    ports:
      - 3000:3000
    depends_on:
      - mongo

  tuckerfrontend:
    image: tucker-frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - tuckerbackend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
